package com.xgx.dw;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.xgx.dw.PricingBean;

import com.xgx.dw.PricingBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pricingBeanDaoConfig;

    private final PricingBeanDao pricingBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pricingBeanDaoConfig = daoConfigMap.get(PricingBeanDao.class).clone();
        pricingBeanDaoConfig.initIdentityScope(type);

        pricingBeanDao = new PricingBeanDao(pricingBeanDaoConfig, this);

        registerDao(PricingBean.class, pricingBeanDao);
    }
    
    public void clear() {
        pricingBeanDaoConfig.getIdentityScope().clear();
    }

    public PricingBeanDao getPricingBeanDao() {
        return pricingBeanDao;
    }

}
