package com.xgx.dw;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table Pricing.
 */
public class PricingBean implements Serializable {

    private String id;
    private String userPrimaryid;
    private String pid;
    private String price;
    private String bjprice;
    private String spotpriceId;
    private String userId;
    private String userName;
    private String adminName;
    private String adminPhone;
    private String storeId;
    private String storeName;
    private String storeAddress;
    private String transformerId;
    private String transformerName;
    private String createTime;
    private String type;
    private String finishtype;
    private String ime;

    public PricingBean() {
    }

    public PricingBean(String id) {
        this.id = id;
    }

    public PricingBean(String id, String userPrimaryid, String pid, String price, String bjprice, String spotpriceId, String userId, String userName, String adminName, String adminPhone, String storeId, String storeName, String storeAddress, String transformerId, String transformerName, String createTime, String type, String finishtype, String ime) {
        this.id = id;
        this.userPrimaryid = userPrimaryid;
        this.pid = pid;
        this.price = price;
        this.bjprice = bjprice;
        this.spotpriceId = spotpriceId;
        this.userId = userId;
        this.userName = userName;
        this.adminName = adminName;
        this.adminPhone = adminPhone;
        this.storeId = storeId;
        this.storeName = storeName;
        this.storeAddress = storeAddress;
        this.transformerId = transformerId;
        this.transformerName = transformerName;
        this.createTime = createTime;
        this.type = type;
        this.finishtype = finishtype;
        this.ime = ime;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUserPrimaryid() {
        return userPrimaryid;
    }

    public void setUserPrimaryid(String userPrimaryid) {
        this.userPrimaryid = userPrimaryid;
    }

    public String getPid() {
        return pid;
    }

    public void setPid(String pid) {
        this.pid = pid;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getBjprice() {
        return bjprice;
    }

    public void setBjprice(String bjprice) {
        this.bjprice = bjprice;
    }

    public String getSpotpriceId() {
        return spotpriceId;
    }

    public void setSpotpriceId(String spotpriceId) {
        this.spotpriceId = spotpriceId;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getAdminName() {
        return adminName;
    }

    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }

    public String getAdminPhone() {
        return adminPhone;
    }

    public void setAdminPhone(String adminPhone) {
        this.adminPhone = adminPhone;
    }

    public String getStoreId() {
        return storeId;
    }

    public void setStoreId(String storeId) {
        this.storeId = storeId;
    }

    public String getStoreName() {
        return storeName;
    }

    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }

    public String getStoreAddress() {
        return storeAddress;
    }

    public void setStoreAddress(String storeAddress) {
        this.storeAddress = storeAddress;
    }

    public String getTransformerId() {
        return transformerId;
    }

    public void setTransformerId(String transformerId) {
        this.transformerId = transformerId;
    }

    public String getTransformerName() {
        return transformerName;
    }

    public void setTransformerName(String transformerName) {
        this.transformerName = transformerName;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getFinishtype() {
        return finishtype;
    }

    public void setFinishtype(String finishtype) {
        this.finishtype = finishtype;
    }

    public String getIme() {
        return ime;
    }

    public void setIme(String ime) {
        this.ime = ime;
    }

}
