package com.xgx.dw;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table SearchDlLog.
 */
public class SearchDlLog implements Serializable {

    private String id;
    private String content;
    private String type;
    private String userId;

    public SearchDlLog() {
    }

    public SearchDlLog(String id) {
        this.id = id;
    }

    public SearchDlLog(String id, String content, String type, String userId) {
        this.id = id;
        this.content = content;
        this.type = type;
        this.userId = userId;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

}
