package com.xgx.dw;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table SpotPricing.
 */
public class SpotPricingBean implements Serializable {

    private String id;
    private String name;
    private String store_id;
    private String storename;
    private String type;
    private String price_count;
    private String pointed_price;
    private String peek_price;
    private String flat_price;
    private String valley_price;

    public SpotPricingBean() {
    }

    public SpotPricingBean(String id) {
        this.id = id;
    }

    public SpotPricingBean(String id, String name, String store_id, String storename, String type, String price_count, String pointed_price, String peek_price, String flat_price, String valley_price) {
        this.id = id;
        this.name = name;
        this.store_id = store_id;
        this.storename = storename;
        this.type = type;
        this.price_count = price_count;
        this.pointed_price = pointed_price;
        this.peek_price = peek_price;
        this.flat_price = flat_price;
        this.valley_price = valley_price;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getStore_id() {
        return store_id;
    }

    public void setStore_id(String store_id) {
        this.store_id = store_id;
    }

    public String getStorename() {
        return storename;
    }

    public void setStorename(String storename) {
        this.storename = storename;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getPrice_count() {
        return price_count;
    }

    public void setPrice_count(String price_count) {
        this.price_count = price_count;
    }

    public String getPointed_price() {
        return pointed_price;
    }

    public void setPointed_price(String pointed_price) {
        this.pointed_price = pointed_price;
    }

    public String getPeek_price() {
        return peek_price;
    }

    public void setPeek_price(String peek_price) {
        this.peek_price = peek_price;
    }

    public String getFlat_price() {
        return flat_price;
    }

    public void setFlat_price(String flat_price) {
        this.flat_price = flat_price;
    }

    public String getValley_price() {
        return valley_price;
    }

    public void setValley_price(String valley_price) {
        this.valley_price = valley_price;
    }

}
