package com.xgx.dw;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table Store.
 */
public class StoreBean implements Serializable {


    private String id;
    private String name;
    private String address;
    private String linkman;
    private String contact_way;

    public StoreBean() {
    }

    public StoreBean(String id) {
        this.id = id;
    }

    public StoreBean(String id, String name, String address, String linkman, String contact_way) {
        this.id = id;
        this.name = name;
        this.address = address;
        this.linkman = linkman;
        this.contact_way = contact_way;
    }

    public StoreBean(String id, String name) {
        this.id = id;
        this.name = name;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getLinkman() {
        return linkman;
    }

    public void setLinkman(String linkman) {
        this.linkman = linkman;
    }

    public String getContact_way() {
        return contact_way;
    }

    public void setContact_way(String contact_way) {
        this.contact_way = contact_way;
    }

}
