package com.xgx.dw;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table Transformer.
 */
public class TransformerBean implements Serializable {

    private String id;
    private String name;
    private String store_id;
    private String store_name;

    public TransformerBean() {
    }

    public TransformerBean(String id) {
        this.id = id;
    }

    public TransformerBean(String id, String name, String store_id, String store_name) {
        this.id = id;
        this.name = name;
        this.store_id = store_id;
        this.store_name = store_name;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getStore_id() {
        return store_id;
    }

    public void setStore_id(String store_id) {
        this.store_id = store_id;
    }

    public String getStore_name() {
        return store_name;
    }

    public void setStore_name(String store_name) {
        this.store_name = store_name;
    }

}
