package com.xgx.dw;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table user.
 */
public class UserBean {

    private String bianhao;
    private String xingming;
    private String mima;
    private String bumen;
    private String bumenmc;
    private String shenfenzheng;
    private String lianxifangshi;
    private String zhuzhi;
    private String recid;
    private String createtime;
    private String deleted;
    private String countyid;
    private String countyname;
    private String audiotype;
    private String bumenmcfull;
    private String bumenbhfull;
    private String sg186pwd;
    private String handleno;
    private String operno;
    private String remark;

    public UserBean() {
    }

    public UserBean(String bianhao) {
        this.bianhao = bianhao;
    }

    public UserBean(String bianhao, String xingming, String mima, String bumen, String bumenmc, String shenfenzheng, String lianxifangshi, String zhuzhi, String recid, String createtime, String deleted, String countyid, String countyname, String audiotype, String bumenmcfull, String bumenbhfull, String sg186pwd, String handleno, String operno, String remark) {
        this.bianhao = bianhao;
        this.xingming = xingming;
        this.mima = mima;
        this.bumen = bumen;
        this.bumenmc = bumenmc;
        this.shenfenzheng = shenfenzheng;
        this.lianxifangshi = lianxifangshi;
        this.zhuzhi = zhuzhi;
        this.recid = recid;
        this.createtime = createtime;
        this.deleted = deleted;
        this.countyid = countyid;
        this.countyname = countyname;
        this.audiotype = audiotype;
        this.bumenmcfull = bumenmcfull;
        this.bumenbhfull = bumenbhfull;
        this.sg186pwd = sg186pwd;
        this.handleno = handleno;
        this.operno = operno;
        this.remark = remark;
    }

    public String getBianhao() {
        return bianhao;
    }

    public void setBianhao(String bianhao) {
        this.bianhao = bianhao;
    }

    public String getXingming() {
        return xingming;
    }

    public void setXingming(String xingming) {
        this.xingming = xingming;
    }

    public String getMima() {
        return mima;
    }

    public void setMima(String mima) {
        this.mima = mima;
    }

    public String getBumen() {
        return bumen;
    }

    public void setBumen(String bumen) {
        this.bumen = bumen;
    }

    public String getBumenmc() {
        return bumenmc;
    }

    public void setBumenmc(String bumenmc) {
        this.bumenmc = bumenmc;
    }

    public String getShenfenzheng() {
        return shenfenzheng;
    }

    public void setShenfenzheng(String shenfenzheng) {
        this.shenfenzheng = shenfenzheng;
    }

    public String getLianxifangshi() {
        return lianxifangshi;
    }

    public void setLianxifangshi(String lianxifangshi) {
        this.lianxifangshi = lianxifangshi;
    }

    public String getZhuzhi() {
        return zhuzhi;
    }

    public void setZhuzhi(String zhuzhi) {
        this.zhuzhi = zhuzhi;
    }

    public String getRecid() {
        return recid;
    }

    public void setRecid(String recid) {
        this.recid = recid;
    }

    public String getCreatetime() {
        return createtime;
    }

    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    public String getDeleted() {
        return deleted;
    }

    public void setDeleted(String deleted) {
        this.deleted = deleted;
    }

    public String getCountyid() {
        return countyid;
    }

    public void setCountyid(String countyid) {
        this.countyid = countyid;
    }

    public String getCountyname() {
        return countyname;
    }

    public void setCountyname(String countyname) {
        this.countyname = countyname;
    }

    public String getAudiotype() {
        return audiotype;
    }

    public void setAudiotype(String audiotype) {
        this.audiotype = audiotype;
    }

    public String getBumenmcfull() {
        return bumenmcfull;
    }

    public void setBumenmcfull(String bumenmcfull) {
        this.bumenmcfull = bumenmcfull;
    }

    public String getBumenbhfull() {
        return bumenbhfull;
    }

    public void setBumenbhfull(String bumenbhfull) {
        this.bumenbhfull = bumenbhfull;
    }

    public String getSg186pwd() {
        return sg186pwd;
    }

    public void setSg186pwd(String sg186pwd) {
        this.sg186pwd = sg186pwd;
    }

    public String getHandleno() {
        return handleno;
    }

    public void setHandleno(String handleno) {
        this.handleno = handleno;
    }

    public String getOperno() {
        return operno;
    }

    public void setOperno(String operno) {
        this.operno = operno;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

}
