package com.xgx.dw;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table user.
 */
public class UserBean implements Serializable {

    private String id;
    private String userId;
    private String userName;
    private String password;
    private String type;
    private String storeId;
    private String storeName;
    private String isBuy;
    private String isTest;
    private String transformerId;
    private String transformerName;
    private String voltageRatio;
    private String currentRatio;
    private String price;
    private String phone;
    private String createTime;
    private String remark;
    private String ime;
    private String ecodeType;

    public UserBean() {
    }

    public UserBean(String id, String userId, String name, String pwd, String type, String ime) {
        this.userId = userId;
        this.id = id;
        this.userName = name;
        this.password = pwd;
        this.type = type;
        this.ime = ime;
    }

    public UserBean(String id) {
        this.id = id;
    }

    public UserBean(String id, String userId, String userName, String password, String type, String storeId, String storeName, String isBuy, String isTest, String transformerId, String transformerName, String voltageRatio, String currentRatio, String price, String phone, String createTime, String remark, String ime, String ecodeType) {
        this.id = id;
        this.userId = userId;
        this.userName = userName;
        this.password = password;
        this.type = type;
        this.storeId = storeId;
        this.storeName = storeName;
        this.isBuy = isBuy;
        this.isTest = isTest;
        this.transformerId = transformerId;
        this.transformerName = transformerName;
        this.voltageRatio = voltageRatio;
        this.currentRatio = currentRatio;
        this.price = price;
        this.phone = phone;
        this.createTime = createTime;
        this.remark = remark;
        this.ime = ime;
        this.ecodeType = ecodeType;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getStoreId() {
        return storeId;
    }

    public void setStoreId(String storeId) {
        this.storeId = storeId;
    }

    public String getStoreName() {
        return storeName;
    }

    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }

    public String getIsBuy() {
        return isBuy == null ? "" : isBuy;
    }

    public void setIsBuy(String isBuy) {
        this.isBuy = isBuy;
    }

    public String getIsTest() {
        return isTest == null ? "" : isTest;
    }

    public void setIsTest(String isTest) {
        this.isTest = isTest;
    }

    public String getTransformerId() {
        return transformerId;
    }

    public void setTransformerId(String transformerId) {
        this.transformerId = transformerId;
    }

    public String getTransformerName() {
        return transformerName;
    }

    public void setTransformerName(String transformerName) {
        this.transformerName = transformerName;
    }

    public String getVoltageRatio() {
        return voltageRatio;
    }

    public void setVoltageRatio(String voltageRatio) {
        this.voltageRatio = voltageRatio;
    }

    public String getCurrentRatio() {
        return currentRatio;
    }

    public void setCurrentRatio(String currentRatio) {
        this.currentRatio = currentRatio;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getIme() {
        return ime;
    }

    public void setIme(String ime) {
        this.ime = ime;
    }

    public String getEcodeType() {
        return ecodeType;
    }

    public void setEcodeType(String ecodeType) {
        this.ecodeType = ecodeType;
    }

}
